export const jabatan = [
	"Kepala Madrasah",
	"Kepala Tata Usaha",
	"Wakil Kepala Madrasah",
	"Staf Tata Usaha",
	"Wali Kelas",
	"Tokoh Agama",
	"Guru BP/BK",
	"Dewan Guru",
];

export const mataPelajaran = [
	"Bahasa Indonesia",
	"Akidah Akhlak",
	"Matematika",
	"Al-Qur'an Hadits",
	"Bahasa Inggris",
	"Fiqih",
	"Bahasa Arab",
	"Matematika Peminatan",
	"Sejarah Peminatan",
	"Bahasa Arab Peminatan",
	"Sejarah Kebudayaan Islam",
	"Biologi",
	"Sosiologi",
	"Ilmu Hadits",
	"Pendidikan Pancasila dan Kewarganegaraan",
	"Kimia",
	"Geografi",
	"Ushul Fiqih",
	"Fisika",
	"Ekonomi",
	"Ilmu Tafsir",
	"Sejarah Indonesia",
	"Prakarya dan Kewirausahaan",
	"Mulok",
	"Pendidikan Jasmani, Olahraga, Kesehatan",
	"Seni Budaya",
	"Keterampilan",
];
